### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by allanlundhansen** [JackAdams/meteor-editable-list#2]
Thx for a good package!

Not sure about feature request :? would really like to see this package support collections with array of objects is this possible ?

**Comment by JackAdams** [comment]
I hear you -- I often find myself wishing for this feature. #1 was exactly the same request. Unfortunately, the refactor path is too complex for me to try it at the moment.

**Comment by JackAdams** [comment]
Oh ... wait a minute!  I just wrote a package the other day that might make this possible [babrahams:editable-json](http://meteorpad.com/pad/AphADo6eR4aiJmNzS/Editable%20JSON%20Example).  I'll have a think about it.

**Comment by allanlundhansen** [comment]
awesome if it is possible! and sry for not checking #1 beforehand it was @ 1am ;)

**Comment by JackAdams** [comment]
The biggest problem is the UI for this.  It could look something like [this](http://meteorpad.com/pad/AphADo6eR4aiJmNzS/Editable%20JSON%20Example) (which no-one would ever use), or it could be a simple form-style list of key-value pairs where the values are input fields.  Neither of these is likely to get any real-world use.

Or, in an entirely different paradigm (but probably the one people would actually use) the UI could just be identical to the current one, but editing only targets a certain field in the objects in the array.  But then there's the question of which fields get included when an object gets pushed to the array (do we need a set of defaults).

I'll keep thinking about it, but the complexity increase of the package seems to spiral out of control as soon as we use objects instead of strings.  I'm closing this issue for the moment as out-of-scope for the package.

**Comment by JackAdams** [comment]
This might be of interest:
https://github.com/JackAdams/meteor-editable-text/issues/21
